### ISSUE TITLE
Separate channel export function does not work.

### ISSUE THREAD

**Issue by eithereor** [Dn-Programming-Core-Management/Dn-FamiTracker#14]
![image4](https://user-images.githubusercontent.com/75454345/101097566-c799a080-3597-11eb-99ed-8aa781b062e7.png)

When I tick the "Separate Channel export" box in WAV export, I get the following error "Could not open the file!"
I have tried with 2a03 projects as well as others with expansion chips, but multichannel export is not working in any of them.

**Comment by 0x5066** [comment]
have you checked if you have write permission for the folder?

**Comment by eithereor** [comment]
Hello, I checked the folder and I had the right permissions to write.
I finally found the cause. My antivirus program (Avast) was blocking Dn-Famitracker from writing files.
