### ISSUE TITLE
Frame editor is broken in master

### ISSUE THREAD

**Issue by nyanpasu64** [Dn-Programming-Core-Management/Dn-FamiTracker#15]
The frame editor has received some changes in master... causing lots of regressions unfortunately.

I tested an old master revision (b6aa6cf6c3331e47878d65fb6b6e19712eda6880), and there have been no substantial code changes between then and now (7022b896a68192e9e9c09ceca7f3065773c679a5).

- [x] In bookmarked rows, the background color covers up text.
![Bookmark row background covers text](https://user-images.githubusercontent.com/913957/101816024-4f6e3600-3ad5-11eb-8c07-c2f99989ed5a.png)
- [x] As far as I know, there's no option to show the full width of frame editor and disable horizontal scrolling.
- [x] Clicking on the frame editor does not move the cursor.
- [x] Cannot click-drag (create a selection) to scroll horizontally.
- [x] If you click-drag to create a selection, then move the mouse near the top of the screen to scroll up, scrolling stops when row 0 is still not visible (because it's covered by the new channel names header).
![image](https://user-images.githubusercontent.com/913957/101816547-01a5fd80-3ad6-11eb-952c-ff38b0a0c7e4.png)
- Related: If you click-drag to create a selection, move the mouse near the top/bottom to scroll up/down, and your mouse leaves the frame editor, it stops scrolling. This was already an issue in 0CC. In my opinion, it should scroll when your mouse cursor is (current behavior, optional) near the edge of the widget, and also (required) outside the widget.
  - Semi-related: With "free cursor edit" (actually unlocking scroll from cursor) enabled, right now if you mouse-select near the top of the screen, the cursor moves up. When it reaches the previous pattern, the pattern data jumps in position. This makes mouse-select almost useless for the top rows.
https://youtu.be/STilYOKb7JU

**Comment by Gumball2415** [comment]
i can't seem to replicate the first and third issue, can you send the module in the screenshot?
are there any steps to reproduce the issue?

**Comment by nyanpasu64** [comment]
- [x] Frame editor size isn't remembered when you close the program. (Should it be?)
- [x] If you go from 6 or more channels shown to a blank 2A03 module, the left arrow is shown but does nothing.
- [x] If you go from a 20 channel module (all shown) to a 10 channel module, you have to press the left arrow 11 times to start shrinking.
