### ISSUE TITLE
Program name

### ISSUE THREAD

**Issue by Pegmode** [Dn-Programming-Core-Management/Dn-FamiTracker#37]
> The meaning of the name "Dn" is whatever you wish it to be.

So what you're saying is that the official name for Dn-FamiTracker is "Deez Nuts FamiTracker"? 😏

**Comment by Gumball2415** [comment]
What it means is that the meaning of Dn is defined to be subjective, and therefore can have no official definition.

**Comment by Gumball2415** [comment]
The definition has been updated, please refer to the readme.
