### ISSUE TITLE
VRC7 Hardware Presets Reading Improperly

### ISSUE THREAD

**Issue by Also-NK** [Dn-Programming-Core-Management/Dn-FamiTracker#50]
The jump to v0.3 was a warm welcome, what with its features, but I unfortunately found a somewhat annoying bug while messing with the VRC7 instrument presets. The presets **play** as intended (Patch 1 sounds exactly like Patch 1, Patch 2 sounds exactly like Patch 2, etc), but the instrument **data** that's read is completely different from their intended data. The preset data itself is read as follows:

1: $13 $41 $14 $0D $D8 $F6 $23 $12
2: $31 $61 $0C $07 $A8 $64 $61 $27
3: $02 $01 $06 $00 $A3 $E2 $F4 $F4
4: $23 $21 $22 $17 $A2 $72 $01 $17
5: $B5 $01 $0F $0F $A8 $A5 $51 $02
6: $71 $23 $11 $06 $65 $74 $18 $16
7: $61 $63 $0C $00 $94 $C0 $33 $F6
8: $01 $01 $18 $0F $DF $F8 $6A $6D
9: $05 $01 $00 $00 $F8 $AA $59 $55
A: $00 $00 $00 $00 $00 $00 $00 $00
B: $00 $00 $00 $00 $00 $00 $00 $00
C: $00 $00 $00 $00 $00 $00 $00 $00
D: $00 $00 $00 $00 $00 $00 $00 $00
E: $00 $00 $00 $00 $00 $00 $00 $00
F: $00 $00 $00 $00 $00 $00 $00 $00

These exact "bugged" presets are consistent throughout each and every patchset.

**Comment by TakuikaNinja** [comment]
Yeah, I can confirm the patch data obtained from copying the preset patch data is messed up.

**Comment by TakuikaNinja** [comment]
Hmm, it seems like whatever is reading the patch data is indexing the patches incorrectly - it's skipping the odd number patches (1,3,5,7, etc).

**Comment by Gumball2415** [comment]
Upon reading the previous diffs, it seems that [patches before the VRC7 emulation update ](https://github.com/Gumball2415/Dn-FamiTracker/blob/6eaa2dc77059366eec2312e1feded89ecc831d46/Source/APU/ext/vrc7tone.h)(6eaa2dc77059366eec2312e1feded89ecc831d46) were encoded with 8 bytes of 0x00 after each patch. This might have caused the patch skipping. I will investigate further.

**Comment by Gumball2415** [comment]
Fixed by #60.
