### ISSUE TITLE
[feature request] custom VRC7 patch set

### ISSUE THREAD

**Issue by galap-1** [Dn-Programming-Core-Management/Dn-FamiTracker#64]
With the ability to switch between different VRC7 hardware patch sets (some of which , a cool extension that immediately suggests itself is to be able to use your own, user-defined sets of patches. this would essentially get around the vrc7's limitation of only one user-defined patch at a time, which would really expand the capabilities of what you could do without (hopefully) too much difficulty of implementation.

**Comment by Gumball2415** [comment]
Export compatibility might be an issue if one were to overwrite the hardware patches with custom ones. The reason for swappable hardware patches is for compatibility with older modules, which might depend on older versions of VRC7 hardware patches.

**Comment by galap-1** [comment]
Makes sense, but some of those preset patch sets in there are quite different from the real ones already (e.g. 281B/2413) and thus wouldn't be interpreted correctly by things you exported for. I personally wouldn't really have a problem with being able to select patch sets that wouldn't export.

**Comment by Gumball2415** [comment]
The patches I pulled from were from NSFPlay's hidden hardware patch options, so technically it _can_ be played back externally through it. 

There are other games which use the same YM2413 soundchip but with different hardware patches from Lagrange Point (for instance, Family Noraebang), so I see how this can also be applicable for homebrew applications where one developer uses custom hardware patches.

**Comment by galap-1** [comment]
I looked up Noraebang, didn't know about that! That's a really interesting game, and some great music!

**Comment by Gumball2415** [comment]
In one of the NSFe metadata fields, [there's room for an entire custom hardware patch set](https://wiki.nesdev.org/w/index.php/NSFe#VRC7). Though this is intended for OPLL clones with varying hardware patchsets, this can also enable entire custom patchsets, though at the cost of not being able to accurately play it in hardware.
