### ISSUE TITLE
Per-module audio profiles?

### ISSUE THREAD

**Issue by nyanpasu64** [Dn-Programming-Core-Management/Dn-FamiTracker#68]
Should add a way to enable on a per-module basis:

- Don't exponentially reduce volume levels when enabling more expansion chips
- Make VRC7 decrease volume when enabling more expansion chips
- Change 2A03 mixing levels and nonlinear mixing equation to match hardware
- Pick which VRC7 patch set to use? (old OPLL patches for old modules, new hardware-ripped patches, etc... is it useful to add a brand-new flag for restoring long-dead patches used in years-old modules? It would also be useful for new fantasy-chip modules I suppose.)
- etc.

**Comment by pinobatch** [comment]
[NSFe](https://wiki.nesdev.com/w/index.php/NSFe) has chunks `VRC7` and `mixe` that could handle some of those, though not relative balance within the TND pin.
