### ISSUE TITLE
create new documents with an empty instrument?

### ISSUE THREAD

**Issue by nyanpasu64** [Dn-Programming-Core-Management/Dn-FamiTracker#77]
to make it easier for noobs to make sound

**Comment by N-SPC700** [comment]
I support this. Deflemask does a similar thing too. I would also encourage if we did something similar to Deflemask, where we also add a simple decay macro into it.

**Comment by nyanpasu64** [comment]
does creating an empty instrument at startup work well along with c84e280001a0b7aa2a8dd143d75c8e65575c6703 "Blank new instrument names on creation"? personally i dislike that commit, but i haven't spoken with "Some users find that new instruments named "New instrument" is often hard to deal with".

should the empty instrument have the default name, or a different one ("New Instrument" anyway)?

**Comment by Gumball2415** [comment]
Should the new instrument have a volume macro too? or should I leave it blank?

**Comment by N-SPC700** [comment]
I think a simple macro (that goes from volume 15 to volume 0) would help demonstrate the volume macro editor to those who aren't too well versed in doing anything in FT. Deflemask has a preset decay macro for all NES modules, that's the same exact thing (the 15 to 0 volume decay).

**Comment by nyanpasu64** [comment]
Should all new instruments come with a volume macro, or just the document's first instrument?

I think it's bad for all new instruments to come with a volume macro. If so, then every time you create an instrument will waste a volume macro slot forever-ish, since FamiTracker won't erase macros and reuse the number for the next instrument. Unchecking Volume won't help, and neither will switching to a previous instrument's volume macro. In order to convince FamiTracker to reuse a slot, you must clear the envelope, *then* uncheck Volume or switch to a different number.

**Comment by N-SPC700** [comment]
I think it should just be the first instrument, simply for demonstration purposes. It wouldn't make much sense if subsequent instruments had their very own decay macro slapped on, as it'd also waste space.

**Comment by Gumball2415** [comment]
this issue is related with nyanpasu64/j0CC-FamiTracker#106.
